name: RexDex's personal page 
title: RexDex's personal page

description: My personal source code repository, enjoy!
email: rexdexpl@gmail.com

url: "http://rexdex.pl"
github_username: rexdex
baseurl: ""

markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
